export const GET_DATA_JABATAN_SUCCESS = 'GET_DATA_JABATAN_SUCCESS';
export const GET_DATA_JABATAN_FAILURE = 'GET_DATA_JABATAN_FAILURE';
export const CREATE_DATA_JABATAN_SUCCESS = 'CREATE_DATA_JABATAN_SUCCESS';
export const CREATE_DATA_JABATAN_FAILURE = 'CREATE_DATA_JABATAN_FAILURE';
export const UPDATE_DATA_JABATAN_SUCCESS = 'UPDATE_DATA_JABATAN_SUCCESS';
export const UPDATE_DATA_JABATAN_FAILURE = 'UPDATE_DATA_JABATAN_FAILURE';
export const DELETE_DATA_JABATAN_SUCCESS = 'DELETE_DATA_JABATAN_SUCCESS';
export const DELETE_DATA_JABATAN_FAILURE = 'DELETE_DATA_JABATAN_FAILURE';
