export const GET_DATA_POTONGAN_SUCCESS = 'GET_DATA_POTONGAN_SUCCESS';
export const GET_DATA_POTONGAN_FAILURE = 'GET_DATA_POTONGAN_FAILURE';
export const CREATE_DATA_POTONGAN_SUCCESS = 'CREATE_DATA_POTONGAN_SUCCESS';
export const CREATE_DATA_POTONGAN_FAILURE = 'CREATE_DATA_POTONGAN_FAILURE';
export const UPDATE_DATA_POTONGAN_SUCCESS = 'UPDATE_DATA_POTONGAN_SUCCESS';
export const UPDATE_DATA_POTONGAN_FAILURE = 'UPDATE_DATA_POTONGAN_FAILURE';
export const DELETE_DATA_POTONGAN_SUCCESS = 'DELETE_DATA_POTONGAN_SUCCESS';
export const DELETE_DATA_POTONGAN_FAILURE = 'DELETE_DATA_POTONGAN_FAILURE';
