### Get All Data Kehadiran
GET  http://localhost:5000/data_kehadiran

### Create Data Kehadiran
POST  http://localhost:5000/data_kehadiran
Content-Type: application/json

{
    "hadir": 9,
    "sakit": 2,
    "alpha": 1
}

### UPDATE data kehadiran
PATCH  http://localhost:5000/data_kehadiran/update/11
Content-Type: application/json

{
    "hadir": "2",
    "sakit": "2",
    "alpha": "2"
}

### DELETE Data Kehadiran
DELETE http://localhost:5000/data_kehadiran/10