######################
###### Laporan #######
######################


########### Laporan Gaji ###########

### get All Data Laporan Gaji
GET http://localhost:5000/laporan/gaji

### get All Data Laporan Gaji By Name
GET http://localhost:5000/laporan/gaji/name/nana

### get All Data Laporan Gaji By Month
GET http://localhost:5000/laporan/gaji/month/januari

### get All Data Laporan Gaji By Year
GET http://localhost:5000/laporan/gaji/year/2023



########### Laporan Absensi ###########
### get All Data Laporan Absensi By Month
GET http://localhost:5000/laporan/absensi/month/maret

### get All Data Laporan Absensi By Year
GET http://localhost:5000/laporan/absensi/year/2021


###########    Slip Gaji    ###########
### get Slip Gaji By Name
GET http://localhost:5000/laporan/slip_gaji/name/caca

### get Slip Gaji By Month
GET http://localhost:5000/laporan/slip_gaji/month/maret

### get Slip Gaji By Year
GET http://localhost:5000/laporan/slip_gaji/year/2022