export const GET_DATA_KEHADIRAN_SUCCESS = ' GET_DATA_KEHADIRAN_SUCCESS';
export const GET_DATA_KEHADIRAN_FAILURE = ' GET_DATA_KEHADIRAN_FAILURE';
export const CREATE_DATA_KEHADIRAN_SUCCESS = ' CREATE_DATA_KEHADIRAN_SUCCESS';
export const CREATE_DATA_KEHADIRAN_FAILURE = 'CREATE_DATA_KEHADIRAN_FAILURE';
export const UPDATE_DATA_KEHADIRAN_SUCCESS = ' UPDATE_DATA_KEHADIRAN_SUCCESS';
export const UPDATE_DATA_KEHADIRAN_FAILURE = 'UPDATE_DATA_KEHADIRAN_FAILURE';
export const DELETE_DATA_KEHADIRAN_SUCCESS = 'DELETE_DATA_KEHADIRAN_SUCCESS';
export const DELETE_DATA_KEHADIRAN_FAILURE = 'DELETE_DATA_KEHADIRAN_FAILURE';
