export const GET_DATA_GAJI_SUCCESS = 'GET_DATA_GAJI_SUCCESS';
export const GET_DATA_GAJI_FAILURE = 'GET_DATA_GAJI_FAILURE';
export const DELETE_DATA_GAJI_SUCCESS = 'DELETE_DATA_GAJI_SUCCESS';
export const DELETE_DATA_GAJI_FAILURE = 'DELETE_DATA_GAJI_FAILURE';
