import User1 from '../assets/images/user/gilbert.png'
import User2 from '../assets/images/user/user-02.png'
import User3 from '../assets/images/user/user-01.png'
import User4 from '../assets/images/user/user-04.png'

const DataPegawaiPeople = [
    {
        id: 1,
        namaPegawai: "Gilbert Hutapea",
        photo: <img src={User1} alt="Gilbert Hutapea" />,
        nik: "1218052110020002",
        jenisKelamin: "Laki-Laki",
        tanggalMasuk: "15-01-2023",
        status: "Karyawan Tetap",
        hakAkses: "Admin",
    },
    {
        id: 2,
        namaPegawai: "Layla Siregar",
        photo: <img src={User2} alt="Layla Siregar" />,
        nik: "1218052110020003",
        jenisKelamin: "Perempuan",
        tanggalMasuk: "16-02-2023",
        status: "Karyawan Tidak Tetap",
        hakAkses: "Pegawai",
    },
    {
        id: 3,
        namaPegawai: "Zilong Sibarani",
        photo: <img src={User3} alt="Zilong Sibarani" />,
        nik: "1218052110020004",
        jenisKelamin: "Laki-Laki",
        tanggalMasuk: "17-03-2023",
        status: "Karyawan Tetap",
        hakAkses: "Pegawai",
    },
    {
        id: 4,
        namaPegawai: "Nana Silaban",
        photo: <img src={User4} alt="Nana Silaban" />,
        nik: "1218052110020005",
        jenisKelamin: "Perempuan",
        tanggalMasuk: "18-04-2023",
        status: "Karyawan Tidak Tetap",
        hakAkses: "Pegawai",
    },
    {
        id: 5,
        namaPegawai: "Nana Silaban",
        photo: <img src={User3} alt="Nana Silaban" />,
        nik: "1218052110020005",
        jenisKelamin: "Perempuan",
        tanggalMasuk: "18-04-2023",
        status: "Karyawan Tidak Tetap",
        hakAkses: "Pegawai",
    },
    {
        id: 6,
        namaPegawai: "Nana Silaban",
        photo: <img src={User2} alt="Nana Silaban" />,
        nik: "1218052110020005",
        jenisKelamin: "Perempuan",
        tanggalMasuk: "18-04-2023",
        status: "Karyawan Tidak Tetap",
        hakAkses: "Pegawai",
    },
    {
        id: 7,
        namaPegawai: "Nana Silaban",
        photo: <img src={User1} alt="Nana Silaban" />,
        nik: "1218052110020005",
        jenisKelamin: "Perempuan",
        tanggalMasuk: "18-04-2023",
        status: "Karyawan Tidak Tetap",
        hakAkses: "Pegawai",
    },
    {
        id: 8,
        namaPegawai: "Nana Silaban",
        photo: <img src={User4} alt="Nana Silaban" />,
        nik: "1218052110020005",
        jenisKelamin: "Perempuan",
        tanggalMasuk: "18-04-2023",
        status: "Karyawan Tidak Tetap",
        hakAkses: "Pegawai",
    },
    {
        id: 9,
        namaPegawai: "Nana Silaban",
        photo: <img src={User2} alt="Nana Silaban" />,
        nik: "1218052110020005",
        jenisKelamin: "Perempuan",
        tanggalMasuk: "18-04-2023",
        status: "Karyawan Tidak Tetap",
        hakAkses: "Pegawai",
    },
    {
        id: 10,
        namaPegawai: "Nana Silaban",
        photo: <img src={User3} alt="Nana Silaban" />,
        nik: "1218052110020005",
        jenisKelamin: "Perempuan",
        tanggalMasuk: "18-04-2023",
        status: "Karyawan Tidak Tetap",
        hakAkses: "Pegawai",
    },
    {
        id: 11,
        namaPegawai: "Nana Silaban",
        photo: <img src={User4} alt="Nana Silaban" />,
        nik: "1218052110020005",
        jenisKelamin: "Perempuan",
        tanggalMasuk: "18-04-2023",
        status: "Karyawan Tidak Tetap",
        hakAkses: "Pegawai",
    },
    {
        id: 12,
        namaPegawai: "Nana Silaban",
        photo: <img src={User1} alt="Nana Silaban" />,
        nik: "1218052110020005",
        jenisKelamin: "Perempuan",
        tanggalMasuk: "18-04-2023",
        status: "Karyawan Tidak Tetap",
        hakAkses: "Pegawai",
    },
    {
        id: 13,
        namaPegawai: "Nana Silaban",
        photo: <img src={User4} alt="Nana Silaban" />,
        nik: "1218052110020005",
        jenisKelamin: "Perempuan",
        tanggalMasuk: "18-04-2023",
        status: "Karyawan Tidak Tetap",
        hakAkses: "Pegawai",
    },
    {
        id: 14,
        namaPegawai: "Nana Silaban",
        photo: <img src={User3} alt="Nana Silaban" />,
        nik: "1218052110020005",
        jenisKelamin: "Perempuan",
        tanggalMasuk: "18-04-2023",
        status: "Karyawan Tidak Tetap",
        hakAkses: "Pegawai",
    },
    {
        id: 15,
        namaPegawai: "Nana Silaban",
        photo: <img src={User2} alt="Nana Silaban" />,
        nik: "1218052110020005",
        jenisKelamin: "Perempuan",
        tanggalMasuk: "18-04-2023",
        status: "Karyawan Tidak Tetap",
        hakAkses: "Pegawai",
    },
    {
        id: 16,
        namaPegawai: "Nana Silaban",
        photo: <img src={User1} alt="Nana Silaban" />,
        nik: "1218052110020005",
        jenisKelamin: "Perempuan",
        tanggalMasuk: "18-04-2023",
        status: "Karyawan Tidak Tetap",
        hakAkses: "Pegawai",
    },
    {
        id: 17,
        namaPegawai: "Nana Silaban",
        photo: <img src={User2} alt="Nana Silaban" />,
        nik: "1218052110020005",
        jenisKelamin: "Perempuan",
        tanggalMasuk: "18-04-2023",
        status: "Karyawan Tidak Tetap",
        hakAkses: "Pegawai",
    },
];

export default DataPegawaiPeople;
